"""added indexes for uploads and blog posts

Revision ID: 3c7df05f0f6
Revises: 3c6af282478
Create Date: 2015-06-29 10:09:45.910965

"""

# revision identifiers, used by Alembic.
revision = '3c7df05f0f6'
down_revision = '3c6af282478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blog_post_published'), 'blog_post', ['published'], unique=False)
    op.create_index(op.f('ix_blog_post_timestamp'), 'blog_post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_uploaded_file_timestamp'), 'uploaded_file', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_file_timestamp'), table_name='uploaded_file')
    op.drop_index(op.f('ix_blog_post_timestamp'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_published'), table_name='blog_post')
    ### end Alembic commands ###
