"""empty migration

Revision ID: 3fa7c3b1be1
Revises: None
Create Date: 2015-03-21 15:01:16.722834

"""

# revision identifiers, used by Alembic.
revision = '3fa7c3b1be1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
